/*
 * HamClock antennas.html page, baked in as a C string.
 * Companion to liveweb.cpp — served on the R/W port as /antennas.html
 */
// LICENSE_BEGIN
// Copyright (c) 2026 David Strickland KR8X
// Contributor to HamClock by Elwood Charles Downey.
// SPDX-License-Identifier: MIT
// See LICENSE file distributed with HamClock for full license text.
// LICENSE_END

#include "HamClock.h"

const char antennas_html[] =
    "<!--\n"
    "  Copyright (c) 2026 David Strickland KR8X\n"
    "  Contributor to HamClock by Elwood Charles Downey.\n"
    "  SPDX-License-Identifier: MIT\n"
    "  See LICENSE file distributed with HamClock for full license text.\n"
    "-->\n"
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "<meta http-equiv=\"Cache-Control\" content=\"no-cache, no-store, must-revalidate\">\n"
    "<meta http-equiv=\"Pragma\" content=\"no-cache\">\n"
    "<meta http-equiv=\"Expires\" content=\"0\">\n"
    "<title>HamClock Antenna Manager</title>\n"
    "<style>\n"
    "  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
    "\n"
    "  body {\n"
    "    font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif;\n"
    "    font-size: 14px;\n"
    "    background: #f5f5f5;\n"
    "    color: #1a1a1a;\n"
    "    padding: 1.5rem 1rem;\n"
    "  }\n"
    "\n"
    "  h1 {\n"
    "    font-size: 20px;\n"
    "    font-weight: 500;\n"
    "    margin-bottom: 0.25rem;\n"
    "  }\n"
    "\n"
    "  .subtitle {\n"
    "    font-size: 13px;\n"
    "    color: #666;\n"
    "    margin-bottom: 1.5rem;\n"
    "  }\n"
    "\n"
    "  .card {\n"
    "    background: #fff;\n"
    "    border: 1px solid #e0e0e0;\n"
    "    border-radius: 10px;\n"
    "    padding: 1rem 1.25rem;\n"
    "    margin-bottom: 1rem;\n"
    "    max-width: 680px;\n"
    "  }\n"
    "\n"
    "  .card-title {\n"
    "    font-size: 11px;\n"
    "    font-weight: 500;\n"
    "    color: #888;\n"
    "    text-transform: uppercase;\n"
    "    letter-spacing: 0.06em;\n"
    "    margin-bottom: 0.75rem;\n"
    "  }\n"
    "\n"
    "  .row {\n"
    "    display: flex;\n"
    "    gap: 10px;\n"
    "    align-items: flex-end;\n"
    "    flex-wrap: wrap;\n"
    "  }\n"
    "\n"
    "  .field {\n"
    "    flex: 1;\n"
    "    min-width: 140px;\n"
    "  }\n"
    "\n"
    "  .field label {\n"
    "    display: block;\n"
    "    font-size: 12px;\n"
    "    color: #666;\n"
    "    margin-bottom: 5px;\n"
    "  }\n"
    "\n"
    "  select, input[type=\"number\"] {\n"
    "    width: 100%;\n"
    "    padding: 7px 10px;\n"
    "    border: 1px solid #ccc;\n"
    "    border-radius: 6px;\n"
    "    font-size: 13px;\n"
    "    background: #fff;\n"
    "    color: #1a1a1a;\n"
    "  }\n"
    "\n"
    "  select:disabled, input:disabled {\n"
    "    background: #f5f5f5;\n"
    "    color: #aaa;\n"
    "  }\n"
    "\n"
    "  select:focus, input:focus {\n"
    "    outline: none;\n"
    "    border-color: #378add;\n"
    "    box-shadow: 0 0 0 2px rgba(55,138,221,0.15);\n"
    "  }\n"
    "\n"
    "  /* Mismatch highlight — orange border + warm tint */\n"
    "  select.mismatch, input.mismatch {\n"
    "    border-color: #d97706;\n"
    "    background: #fffbeb;\n"
    "    box-shadow: 0 0 0 2px rgba(217,119,6,0.15);\n"
    "  }\n"
    "\n"
    "  button {\n"
    "    padding: 7px 16px;\n"
    "    font-size: 13px;\n"
    "    border-radius: 6px;\n"
    "    cursor: pointer;\n"
    "    border: 1px solid #ccc;\n"
    "    background: transparent;\n"
    "    color: #1a1a1a;\n"
    "    white-space: nowrap;\n"
    "    transition: background 0.1s;\n"
    "  }\n"
    "\n"
    "  button:hover:not(:disabled) { background: #f0f0f0; }\n"
    "  button:active:not(:disabled) { transform: scale(0.98); }\n"
    "  button:disabled { opacity: 0.4; cursor: not-allowed; }\n"
    "\n"
    "  .btn-primary {\n"
    "    background: #e6f1fb;\n"
    "    color: #0c447c;\n"
    "    border-color: #85b7eb;\n"
    "  }\n"
    "\n"
    "  .btn-primary:hover:not(:disabled) { background: #cfe4f7; }\n"
    "\n"
    "  .status {\n"
    "    font-size: 12px;\n"
    "    padding: 7px 10px;\n"
    "    border-radius: 6px;\n"
    "    margin-top: 0.75rem;\n"
    "    display: none;\n"
    "  }\n"
    "\n"
    "  .status.ok  { display: block; background: #eaf3de; color: #27500a; }\n"
    "  .status.err { display: block; background: #fcebeb; color: #791f1f; }\n"
    "  .status.inf { display: block; background: #f0f0f0; color: #555; }\n"
    "  .status.warn { display: block; background: #fff7e6; color: #7c4a00; border: 1px solid #f0c070; }\n"
    "\n"
    "  .badge {\n"
    "    display: none;\n"
    "    font-size: 11px;\n"
    "    padding: 2px 7px;\n"
    "    border-radius: 5px;\n"
    "    background: #eaf3de;\n"
    "    color: #27500a;\n"
    "    margin-left: 8px;\n"
    "    vertical-align: middle;\n"
    "  }\n"
    "\n"
    "  /* Mismatch badge — shown next to field label when backend overrode value */\n"
    "  .mismatch-badge {\n"
    "    display: none;\n"
    "    font-size: 11px;\n"
    "    padding: 2px 7px;\n"
    "    border-radius: 5px;\n"
    "    background: #fff3cd;\n"
    "    color: #7c4a00;\n"
    "    border: 1px solid #f0c070;\n"
    "    margin-left: 6px;\n"
    "    vertical-align: middle;\n"
    "  }\n"
    "\n"
    "  .mismatch-badge.visible { display: inline; }\n"
    "\n"
    "  .meta {\n"
    "    font-size: 12px;\n"
    "    color: #999;\n"
    "    margin-top: 6px;\n"
    "  }\n"
    "\n"
    "  .ctrl-row {\n"
    "    display: flex;\n"
    "    gap: 10px;\n"
    "    align-items: center;\n"
    "    flex-wrap: wrap;\n"
    "  }\n"
    "\n"
    "  .ctrl-row label {\n"
    "    font-size: 12px;\n"
    "    color: #666;\n"
    "    min-width: 120px;\n"
    "  }\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<h1>Antenna manager</h1>\n"
    "<p class=\"subtitle\">Controls HamClock antenna selection - DE, DX index and DE/DX control mode</p>\n"
    "\n"
    "<div id=\"st-load\" class=\"status\" style=\"max-width:680px; margin-bottom:1rem;\"></div>\n"
    "\n"
    "<div class=\"card\">\n"
    "  <div class=\"card-title\">\n"
    "    DE/DX antenna control mode\n"
    "    <span id=\"mm-control\" class=\"mismatch-badge\">&#9888; backend used different value</span>\n"
    "  </div>\n"
    "  <div class=\"ctrl-row\">\n"
    "    <label>antdedxcontrol</label>\n"
    "    <select id=\"sel-control\" disabled style=\"width:220px\">\n"
    "      <option value=\"0\">0 - neither (manual)</option>\n"
    "      <option value=\"1\">1 - DE antenna active</option>\n"
    "      <option value=\"2\">2 - DX antenna active</option>\n"
    "      <option value=\"3\">3 - both active</option>\n"
    "    </select>\n"
    "    <button class=\"btn-primary\" id=\"btn-control\" onclick=\"setControl()\" disabled>Set</button>\n"
    "  </div>\n"
    "  <p class=\"meta\">Controls which antenna index is sent to the backend</p>\n"
    "  <div id=\"st-control\" class=\"status\"></div>\n"
    "</div>\n"
    "\n"
    "<div class=\"card\">\n"
    "  <div class=\"card-title\">\n"
    "    DE antenna\n"
    "    <span id=\"de-badge\" class=\"badge\"></span>\n"
    "  </div>\n"
    "  <div class=\"row\">\n"
    "    <div class=\"field\">\n"
    "      <label>\n"
    "        Antenna (antdeindex)\n"
    "        <span id=\"mm-deindex\" class=\"mismatch-badge\">&#9888; backend used different value</span>\n"
    "      </label>\n"
    "      <select id=\"sel-de\" disabled>\n"
    "        <option>-- loading --</option>\n"
    "      </select>\n"
    "    </div>\n"
    "    <div class=\"field\" style=\"max-width:140px\">\n"
    "      <label>\n"
    "        Az (antdeaz) deg\n"
    "        <span id=\"mm-deaz\" class=\"mismatch-badge\">&#9888; backend used different value</span>\n"
    "      </label>\n"
    "      <input type=\"number\" id=\"inp-de-az\" min=\"0\" max=\"360\" step=\"0.1\" disabled placeholder=\"0.0\">\n"
    "    </div>\n"
    "    <button class=\"btn-primary\" id=\"btn-de\" onclick=\"setDE()\" disabled>Set DE</button>\n"
    "  </div>\n"
    "  <div id=\"st-de\" class=\"status\"></div>\n"
    "</div>\n"
    "\n"
    "<div class=\"card\">\n"
    "  <div class=\"card-title\">\n"
    "    DX antenna\n"
    "    <span id=\"dx-badge\" class=\"badge\"></span>\n"
    "  </div>\n"
    "  <div class=\"row\">\n"
    "    <div class=\"field\">\n"
    "      <label>\n"
    "        Antenna (antdxindex)\n"
    "        <span id=\"mm-dxindex\" class=\"mismatch-badge\">&#9888; backend used different value</span>\n"
    "      </label>\n"
    "      <select id=\"sel-dx\" disabled>\n"
    "        <option>-- loading --</option>\n"
    "      </select>\n"
    "    </div>\n"
    "    <div class=\"field\" style=\"max-width:140px\">\n"
    "      <label>\n"
    "        Az (antdxaz) deg\n"
    "        <span id=\"mm-dxaz\" class=\"mismatch-badge\">&#9888; backend used different value</span>\n"
    "      </label>\n"
    "      <input type=\"number\" id=\"inp-dx-az\" min=\"0\" max=\"360\" step=\"0.1\" disabled placeholder=\"0.0\">\n"
    "    </div>\n"
    "    <button class=\"btn-primary\" id=\"btn-dx\" onclick=\"setDX()\" disabled>Set DX</button>\n"
    "  </div>\n"
    "  <div id=\"st-dx\" class=\"status\"></div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "// Copyright (c) 2026 David Strickland KR8X\n"
    "// Contributor to HamClock by Elwood Charles Downey.\n"
    "// SPDX-License-Identifier: MIT\n"
    "// See LICENSE file distributed with HamClock for full license text.\n"
    "\n"
    "'use strict';\n"
    "\n"
    "// Each entry: { index: <numeric index from col1>, desc: <description from col3> }\n"
    "let antennaList = [];\n"
    "\n"
    "function setStatus(id, msg, type) {\n"
    "    const el = document.getElementById(id);\n"
    "    el.textContent = msg;\n"
    "    el.className = 'status ' + type;\n"
    "}\n"
    "\n"
    "function clearStatus(id) {\n"
    "    document.getElementById(id).className = 'status';\n"
    "}\n"
    "\n"
    "// All fetches use relative paths -- always same-origin as the page itself.\n"
    "async function getText(path) {\n"
    "    const r = await fetch(path);\n"
    "    if (!r.ok) throw new Error('HTTP ' + r.status);\n"
    "    return r.text();\n"
    "}\n"
    "\n"
    "/* Parse list_antennas.txt output.\n"
    " * Format (after header lines):\n"
    " *      0 isotrope     ISOTROPE\n"
    " *    256 ccir.000     ISOTROPE\n"
    " *    257 ccir.001     HR 4/4/1\n"
    " * Col 1 (fields[0]) = numeric index used in set_antennas\n"
    " * Col 2 (fields[1]) = model name (ignored)\n"
    " * Col 3+ (fields[2+]) = description (may contain spaces)\n"
    " * Skip the header line \"Index model Description\" and the \"list antennas:\" line.\n"
    " */\n"
    "function parseList(text) {\n"
    "    const result = [];\n"
    "    for (const line of text.split('\\n')) {\n"
    "        const trimmed = line.trim();\n"
    "        if (!trimmed) continue;\n"
    "        if (trimmed.startsWith('list antennas')) continue;\n"
    "        if (trimmed.startsWith('Index')) continue;\n"
    "\n"
    "        const parts = trimmed.split(/\\s+/);\n"
    "        if (parts.length < 3) continue;\n"
    "\n"
    "        const idx = parseInt(parts[0]);\n"
    "        if (isNaN(idx)) continue;\n"
    "\n"
    "        const desc = parts.slice(2).join(' ');\n"
    "        result.push({ index: idx, desc: desc });\n"
    "    }\n"
    "    return result;\n"
    "}\n"
    "\n"
    "/*\n"
    " * Parse get_antennas.txt response.\n"
    " *\n"
    " * Format examples:\n"
    " *   antdedxcontrol: 3 [3]\n"
    " *   antdeindex   set to 1065 [1065] and will be used\n"
    " *   antdeaz      set to 45.0 [45.0] and will be used\n"
    " *   antdxindex   set to 0 [0] and will be used\n"
    " *   antdxaz      set to 0.0 [0.0] and will be used\n"
    " *\n"
    " * For each param we capture:\n"
    " *   requested  = the value after \"set to\" (or after \":\")\n"
    " *   actual     = the value inside [...]\n"
    " *\n"
    " * A mismatch means the backend silently used a different (supported) value.\n"
    " */\n"
    "function parseGetAntennas(text) {\n"
    "    const out = {\n"
    "        deindex:  { requested: null, actual: null },\n"
    "        dxindex:  { requested: null, actual: null },\n"
    "        control:  { requested: null, actual: null },\n"
    "        deaz:     { requested: null, actual: null },\n"
    "        dxaz:     { requested: null, actual: null },\n"
    "    };\n"
    "\n"
    "    for (const line of text.split('\\n')) {\n"
    "        let m;\n"
    "\n"
    "        // antdedxcontrol: 3 [3]\n"
    "        if ((m = line.match(/antdedxcontrol:\\s*(\\d+)\\s*\\[(\\d+)\\]/i))) {\n"
    "            out.control.requested = parseInt(m[1]);\n"
    "            out.control.actual    = parseInt(m[2]);\n"
    "        }\n"
    "        // antdeindex   set to 1114 [0] ... => requested=1114, actual=0\n"
    "        // \\b prevents antdxindex line from also matching\n"
    "        if ((m = line.match(/\\bantdeindex\\b\\s+set to\\s+(\\d+)\\s*\\[(\\d+)\\]/i))) {\n"
    "            out.deindex.requested = parseInt(m[1]);  // value before [ = what was asked\n"
    "            out.deindex.actual    = parseInt(m[2]);  // value inside [] = what backend used\n"
    "        }\n"
    "        // antdxindex   set to 0 [0] ...\n"
    "        if ((m = line.match(/\\bantdxindex\\b\\s+set to\\s+(\\d+)\\s*\\[(\\d+)\\]/i))) {\n"
    "            out.dxindex.requested = parseInt(m[1]);\n"
    "            out.dxindex.actual    = parseInt(m[2]);\n"
    "        }\n"
    "        // antdeaz      set to 45.0 [45.0] ...\n"
    "        if ((m = line.match(/\\bantdeaz\\b\\s+set to\\s+([\\d.]+)\\s*\\[([\\d.]+)\\]/i))) {\n"
    "            out.deaz.requested = parseFloat(m[1]);\n"
    "            out.deaz.actual    = parseFloat(m[2]);\n"
    "        }\n"
    "        // antdxaz      set to 0.0 [0.0] ...\n"
    "        if ((m = line.match(/\\bantdxaz\\b\\s+set to\\s+([\\d.]+)\\s*\\[([\\d.]+)\\]/i))) {\n"
    "            out.dxaz.requested = parseFloat(m[1]);\n"
    "            out.dxaz.actual    = parseFloat(m[2]);\n"
    "        }\n"
    "    }\n"
    "    return out;\n"
    "}\n"
    "\n"
    "/* Populate a select with antenna entries.\n"
    " * option value = the real numeric index (e.g. 256), not the array position.\n"
    " * option text  = \"256 - HR 4/4/1\"\n"
    " */\n"
    "function populateSel(id, list, currentIndex) {\n"
    "    const sel = document.getElementById(id);\n"
    "    sel.innerHTML = '';\n"
    "    for (const ant of list) {\n"
    "        const o = document.createElement('option');\n"
    "        o.value = ant.index;\n"
    "        o.textContent = ant.index + ' - ' + ant.desc;\n"
    "        if (ant.index === currentIndex) o.selected = true;\n"
    "        sel.appendChild(o);\n"
    "    }\n"
    "    sel.disabled = false;\n"
    "}\n"
    "\n"
    "function findDesc(index) {\n"
    "    const ant = antennaList.find(a => a.index === index);\n"
    "    return ant ? ant.desc : '';\n"
    "}\n"
    "\n"
    "function setBadge(id, index) {\n"
    "    const b = document.getElementById(id);\n"
    "    const desc = findDesc(index);\n"
    "    if (index !== null && desc) {\n"
    "        b.textContent = index + ' - ' + desc;\n"
    "        b.style.display = 'inline';\n"
    "    } else {\n"
    "        b.style.display = 'none';\n"
    "    }\n"
    "}\n"
    "\n"
    "/*\n"
    " * Apply mismatch styling to an element and show/hide its warning badge.\n"
    " * elemId      - the select or input element\n"
    " * badgeId     - the mismatch-badge span\n"
    " * requested   - value we asked for\n"
    " * actual      - value backend used\n"
    " * isFloat     - compare as floats (for az fields)\n"
    " * Returns true if mismatch detected.\n"
    " */\n"
    "function applyMismatch(elemId, badgeId, requested, actual, isFloat) {\n"
    "    const el    = document.getElementById(elemId);\n"
    "    const badge = document.getElementById(badgeId);\n"
    "\n"
    "    if (requested === null || actual === null) {\n"
    "        el.classList.remove('mismatch');\n"
    "        badge.classList.remove('visible');\n"
    "        return false;\n"
    "    }\n"
    "\n"
    "    const mismatch = isFloat\n"
    "        ? Math.abs(requested - actual) > 0.001\n"
    "        : requested !== actual;\n"
    "\n"
    "    if (mismatch) {\n"
    "        el.classList.add('mismatch');\n"
    "        badge.classList.add('visible');\n"
    "        badge.title = 'Requested ' + requested + ', backend used ' + actual;\n"
    "    } else {\n"
    "        el.classList.remove('mismatch');\n"
    "        badge.classList.remove('visible');\n"
    "    }\n"
    "    return mismatch;\n"
    "}\n"
    "\n"
    "/*\n"
    " * Apply a full get_antennas state to the UI.\n"
    " * - Populates ALL selects/inputs with the REQUESTED value (what was asked for).\n"
    " * - Shows actual backend value in mismatch badges where different.\n"
    " * - Updates the specified status bar with a context-appropriate message.\n"
    " *   statusId='st-load'    => full summary (all fields)\n"
    " *   statusId='st-de'      => DE-specific message only\n"
    " *   statusId='st-dx'      => DX-specific message only\n"
    " *   statusId='st-control' => control-specific message only\n"
    " */\n"
    "function applyState(state, statusId) {\n"
    "    // Always update all UI fields from the new state\n"
    "    const deIdx = state.deindex.requested !== null ? state.deindex.requested : state.deindex.actual;\n"
    "    const dxIdx = state.dxindex.requested !== null ? state.dxindex.requested : state.dxindex.actual;\n"
    "    const ctrlV = state.control.requested !== null ? state.control.requested : state.control.actual;\n"
    "    const deAzV = state.deaz.requested    !== null ? state.deaz.requested    : state.deaz.actual;\n"
    "    const dxAzV = state.dxaz.requested    !== null ? state.dxaz.requested    : state.dxaz.actual;\n"
    "\n"
    "    if (deIdx !== null) {\n"
    "        populateSel('sel-de', antennaList, deIdx);\n"
    "        setBadge('de-badge', state.deindex.actual);\n"
    "    }\n"
    "    if (dxIdx !== null) {\n"
    "        populateSel('sel-dx', antennaList, dxIdx);\n"
    "        setBadge('dx-badge', state.dxindex.actual);\n"
    "    }\n"
    "    if (ctrlV !== null)\n"
    "        document.getElementById('sel-control').value = ctrlV;\n"
    "\n"
    "    const deAzEl = document.getElementById('inp-de-az');\n"
    "    const dxAzEl = document.getElementById('inp-dx-az');\n"
    "    if (deAzV !== null) deAzEl.value = deAzV.toFixed(1);\n"
    "    if (dxAzV !== null) dxAzEl.value = dxAzV.toFixed(1);\n"
    "\n"
    "    // Check all five fields for mismatches (updates badges/highlighting on all fields)\n"
    "    const mmControl = applyMismatch('sel-control', 'mm-control', state.control.requested, state.control.actual, false);\n"
    "    const mmDeIdx   = applyMismatch('sel-de',      'mm-deindex', state.deindex.requested, state.deindex.actual, false);\n"
    "    const mmDeAz    = applyMismatch('inp-de-az',   'mm-deaz',    state.deaz.requested,    state.deaz.actual,    true);\n"
    "    const mmDxIdx   = applyMismatch('sel-dx',      'mm-dxindex', state.dxindex.requested, state.dxindex.actual, false);\n"
    "    const mmDxAz    = applyMismatch('inp-dx-az',   'mm-dxaz',    state.dxaz.requested,    state.dxaz.actual,    true);\n"
    "\n"
    "    // Build context-specific status message\n"
    "    let msg = '', type = 'ok';\n"
    "\n"
    "    if (statusId === 'st-load') {\n"
    "        // Full summary for page load\n"
    "        let parts = [];\n"
    "        if (state.deindex.actual !== null) parts.push('DE: ' + state.deindex.actual + ' (' + findDesc(state.deindex.actual) + ')');\n"
    "        if (state.dxindex.actual !== null) parts.push('DX: ' + state.dxindex.actual + ' (' + findDesc(state.dxindex.actual) + ')');\n"
    "        if (state.control.actual !== null) parts.push('control: ' + state.control.actual);\n"
    "        msg = parts.join(', ');\n"
    "        const allMM = [];\n"
    "        if (mmControl) allMM.push('antdedxcontrol (requested ' + state.control.requested  + ', backend used ' + state.control.actual  + ')');\n"
    "        if (mmDeIdx)   allMM.push('antdeindex (requested '     + state.deindex.requested  + ', backend used ' + state.deindex.actual  + ')');\n"
    "        if (mmDeAz)    allMM.push('antdeaz (requested '        + state.deaz.requested     + ', backend used ' + state.deaz.actual     + ')');\n"
    "        if (mmDxIdx)   allMM.push('antdxindex (requested '     + state.dxindex.requested  + ', backend used ' + state.dxindex.actual  + ')');\n"
    "        if (mmDxAz)    allMM.push('antdxaz (requested '        + state.dxaz.requested     + ', backend used ' + state.dxaz.actual     + ')');\n"
    "        if (allMM.length > 0) { msg += ' \\u2014 \\u26a0 Backend does not support: ' + allMM.join('; '); type = 'warn'; }\n"
    "\n"
    "    } else if (statusId === 'st-de') {\n"
    "        const mm = [];\n"
    "        if (mmDeIdx) mm.push('antdeindex (requested ' + state.deindex.requested + ', backend used ' + state.deindex.actual + ')');\n"
    "        if (mmDeAz)  mm.push('antdeaz (requested '    + state.deaz.requested    + ', backend used ' + state.deaz.actual    + ')');\n"
    "        if (mm.length > 0) { msg = '\\u26a0 Backend does not support: ' + mm.join('; '); type = 'warn'; }\n"
    "        else { msg = 'DE antenna set to index ' + state.deindex.actual + ' - ' + findDesc(state.deindex.actual); }\n"
    "\n"
    "    } else if (statusId === 'st-dx') {\n"
    "        const mm = [];\n"
    "        if (mmDxIdx) mm.push('antdxindex (requested ' + state.dxindex.requested + ', backend used ' + state.dxindex.actual + ')');\n"
    "        if (mmDxAz)  mm.push('antdxaz (requested '    + state.dxaz.requested    + ', backend used ' + state.dxaz.actual    + ')');\n"
    "        if (mm.length > 0) { msg = '\\u26a0 Backend does not support: ' + mm.join('; '); type = 'warn'; }\n"
    "        else { msg = 'DX antenna set to index ' + state.dxindex.actual + ' - ' + findDesc(state.dxindex.actual); }\n"
    "\n"
    "    } else if (statusId === 'st-control') {\n"
    "        if (mmControl) { msg = '\\u26a0 Backend does not support antdedxcontrol ' + state.control.requested + ', using ' + state.control.actual; type = 'warn'; }\n"
    "        else           { msg = 'antdedxcontrol set to ' + state.control.actual; }\n"
    "    }\n"
    "\n"
    "    setStatus(statusId, msg, type);\n"
    "    return mmControl || mmDeIdx || mmDeAz || mmDxIdx || mmDxAz;\n"
    "}\n"
    "\n"
    "async function loadAll() {\n"
    "    setStatus('st-load', 'Loading antenna data...', 'inf');\n"
    "    try {\n"
    "        const [listText, stateText] = await Promise.all([\n"
    "            getText('/list_antennas.txt'),\n"
    "            getText('/get_antennas.txt')\n"
    "        ]);\n"
    "\n"
    "        antennaList = parseList(listText);\n"
    "        if (antennaList.length === 0) {\n"
    "            setStatus('st-load', 'No antennas returned from list_antennas.txt', 'err');\n"
    "            return;\n"
    "        }\n"
    "\n"
    "        // Enable all controls\n"
    "        document.getElementById('sel-control').disabled = false;\n"
    "        document.getElementById('btn-control').disabled = false;\n"
    "        document.getElementById('inp-de-az').disabled = false;\n"
    "        document.getElementById('inp-dx-az').disabled = false;\n"
    "        document.getElementById('btn-de').disabled = false;\n"
    "        document.getElementById('btn-dx').disabled = false;\n"
    "\n"
    "        const state = parseGetAntennas(stateText);\n"
    "        const hasMismatch = applyState(state, 'st-load');\n"
    "\n"
    "        // Prefix the load status with antenna count\n"
    "        const countPrefix = antennaList.length + ' antennas loaded \\u2014 ';\n"
    "        const stEl = document.getElementById('st-load');\n"
    "        stEl.textContent = countPrefix + stEl.textContent;\n"
    "\n"
    "    } catch (e) {\n"
    "        setStatus('st-load', 'Failed to load: ' + e.message, 'err');\n"
    "    }\n"
    "}\n"
    "\n"
    "async function setControl() {\n"
    "    const v = document.getElementById('sel-control').value;\n"
    "    clearStatus('st-control');\n"
    "    setStatus('st-control', 'Setting antdedxcontrol=' + v + '...', 'inf');\n"
    "    try {\n"
    "        await getText('/set_antennas?antdedxcontrol=' + v);\n"
    "        const state = parseGetAntennas(await getText('/get_antennas.txt'));\n"
    "        applyState(state, 'st-control');\n"
    "    } catch (e) {\n"
    "        setStatus('st-control', 'Failed: ' + e.message, 'err');\n"
    "    }\n"
    "}\n"
    "\n"
    "async function setDE() {\n"
    "    const idx = parseInt(document.getElementById('sel-de').value);\n"
    "    const az  = document.getElementById('inp-de-az').value;\n"
    "    clearStatus('st-de');\n"
    "    let params = 'antdeindex=' + idx;\n"
    "    if (az !== '') params += '&antdeaz=' + parseFloat(az).toFixed(1);\n"
    "    setStatus('st-de', 'Setting ' + params + '...', 'inf');\n"
    "    try {\n"
    "        await getText('/set_antennas?' + params);\n"
    "        const state = parseGetAntennas(await getText('/get_antennas.txt'));\n"
    "        applyState(state, 'st-de');\n"
    "    } catch (e) {\n"
    "        setStatus('st-de', 'Failed: ' + e.message, 'err');\n"
    "    }\n"
    "}\n"
    "\n"
    "async function setDX() {\n"
    "    const idx = parseInt(document.getElementById('sel-dx').value);\n"
    "    const az  = document.getElementById('inp-dx-az').value;\n"
    "    clearStatus('st-dx');\n"
    "    let params = 'antdxindex=' + idx;\n"
    "    if (az !== '') params += '&antdxaz=' + parseFloat(az).toFixed(1);\n"
    "    setStatus('st-dx', 'Setting ' + params + '...', 'inf');\n"
    "    try {\n"
    "        await getText('/set_antennas?' + params);\n"
    "        const state = parseGetAntennas(await getText('/get_antennas.txt'));\n"
    "        applyState(state, 'st-dx');\n"
    "    } catch (e) {\n"
    "        setStatus('st-dx', 'Failed: ' + e.message, 'err');\n"
    "    }\n"
    "}\n"
    "\n"
    "// Auto-load on page open.\n"
    "window.addEventListener('DOMContentLoaded', loadAll);\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    ;
